### PR TITLE
Use markdown for lists and anchors

### PR DESCRIPTION
**Pull request by widoz**

### CODE REVIEW

**Comment by rmccue** [comment]
Thanks for the PR!

I'm 99% certain that I did this intentionally, since the `[info]` block isn't parsed as Markdown when we import it.

Can you test this [using Jetpack's Markdown support](https://jetpack.com/support/markdown/) and see if it's parsed? You may need to also have [the `info` shortcode registered](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/handbook/inc/callout-boxes.php).

**Comment by widoz** [comment]
@rmccue Uhm, I did the change since within the hanbook the list is malformed.
Btw, I'll perform the test you asked.

**Comment by rmccue** [comment]
Right, but I think the better change would be to add the `</ul>`, because I _think_ Markdown isn't parsed inside `[info]` shortcodes. (Not sure why it's ending up with `< ul>` as text, but I'd bet it's some sort of kses thing.)

**Comment by kadamwhite** [comment]
@rmccue is correct, the Info shortcode will not properly parse markdown so we can't use this syntax inside the shortcode tags. I'll close this and add in the `</ul>` instead.

**Comment by kadamwhite** [comment]
Never mind, superseded by #11 !

**Pull request closed without merging**
