### PR TITLE
Add section about embedding in internal requests

### PR DESCRIPTION
**Pull request by k1sul1**
I rely on custom endpoints that utilize internal requests to the REST API in many projects, but I've been unable to get responses with the embedded data until this day. 

For some reason that I do not know

```php
$request = new WP_REST_Request( 'GET', '/wp/v2/posts' );
$request->set_param( '_embed', 1 );
$response = rest_do_request( $request );
```

does not work. `/wp/v2/posts?_embed=1` as URL doesn't work either. 

Today I dove into the internals because now I really need the embedded data, and managed to find a working solution, albeit ~a bit~ hacky.

```php
global $wp_rest_server;
$request = new WP_REST_Request( 'GET', '/wp/v2/posts' );
$response = rest_do_request($req);
$response->set_data( $wp_rest_server->response_to_data( $response, true ) );

return $response;
```

If the solution I came up with is valid, I'd like to add it to the documentation. And if it isn't, how should it be done?

### CODE REVIEW

**Comment by k1sul1** [comment]
So if I were to mutate the $_GET global and add `_embed` key it would work for internal request also? Or is the code running too late for that?

**Comment by TimothyBJacobs** [comment]
I don't think so. The `_embed` handling only happens in `serve_request()` as well which internal requests do not use.

**Comment by rmccue** [comment]
Any parameters which start with a `_` are "meta-parameters" which control the server's response, not the actual endpoints you're calling. These aren't guaranteed to work on the server (for example, what would `_jsonp` actually mean?). This can be confusing, so possible that we'll change it in the future.

We should note this in the docs as the reason why it's not possible.

**Comment by k1sul1** [comment]
So the way I did it is pretty much the only way to do it currently? 

In this particular use case, I'm sending an URL to my endpoint, and if that URL matches a post, a request is made into that specific posts route and endpoint, and the response is returned as is. So client code doesn't have to care whether the response came from `/wp-json/custom/v1/resolve` or `/wp-json/wp/v2/posts/421`.

This is to retain permalink functionality and draft preview support in single page applications.

**Comment by rmccue** [comment]
Yep, calling the helper yourself is the only way to do it right now. It's not the greatest solution, admittedly.

The functionality you're looking for basically sounds like you want to duplicate WP Rewrite's process for matching paths to posts, right? That's something we don't have a solution for right now, but I'm planning at looking at that in the future.

**Comment by k1sul1** [comment]
Basically. In reality, I don't want anything to do with the rewrite system. That's why I created a separate database table and an async queue to populate the table with permalinks and post ids. 

But there are other use cases that I'd like to use the _embed feature, like when I create a special endpoint like /frontpage that contains everything needed to display the frontpage of our application.

(I'm pretty sick right now so apologies if none of this makes any sense)

**Comment by k1sul1** [comment]
Any chance on getting something on this to the official docs? :slightly_smiling_face: 

I encountered a similar issue while creating a custom endpoint that queries other endpoints. 

```
$restBase = $value['term']->taxonomy->rest_base;
$termId = $value['term']->term_id;
$highlights[$key] = rest_do_request(
  new \WP_REST_Request("GET", "/wp/v2/posts?{$restBase}={$termId}")
)->data;
```

The generated path is `/wp/v2/posts?categories=3`, which works if I paste it into my browser, but the above gives me this. 

```
{
  "code": "rest_no_route",
  "message": "No route was found matching the URL and request method",
   "data": {
     "status": 404
  }
},
```

Since I'm not using "meta parameters", I'm not entirely sure what is wrong. I worked around it, but I think that internal requests to the API deserve an entire section in the docs.

**Comment by TimothyBJacobs** [comment]
@k1sul1 For future reference, you want `WP_REST_Request::from_url()`. The second argument to `WP_REST_Request` is just the actual route path, so only things like `/wp/v2/posts` or `/wp/v2/posts/1`. If you use the `from_url()` method it will parse the URL. But you'll need to use it with `rest_url()`. So `WP_REST_Request::from_url( rest_url( '/wp/v2/posts/?categories=3' ) )`.

Also see this core ticket, [40614](https://core.trac.wordpress.org/ticket/40614).

**Comment by k1sul1** [comment]
Thanks for the tip. I'll refactor tomorrow.

**Pull request merged**
